variable "ami_id" {
  description = "AMI ID (If not, used Ubuntu 20.x)"
  type        = string
  default     = null
}

variable "vpc_id" {
  description = "VPC Id to create the resources"
  type        = string
}

variable "subnet_id" {
  description = "Subnet ID to create the resources (If not, use the first one)"
  type        = string
  default     = null
}

variable "instance_type" {
  description = "Instance size"
  type        = string
  default     = "t2.medium"
}

variable "key_name" {
  description = "SSH key name"
  type        = string
  default     = null
}

variable "infracost_api_key" {
  description = "Infracost API Key generated by infracost register"
  type        = string
  sensitive   = true
}

