variable "instance_type" {
  description = "Instance size"
  type        = string
  default     = "t2.micro"
}

variable "key_name" {
  description = "SSH Key name"
  type        = string
  default     = null
}

variable "infracost_api_key" {
  description = "Infracost API Key generated by infracost register"
  type        = string
  default     = ""
  sensitive   = true
}

variable "tags" {
  type = map(string)
  default = {
    CreatedBy = "Terraform"
    Version   = "1.0.0"
    Name      = "Infracost instance"
  }
}

