#cloud-config
packages:
  - curl
  - git
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# create the docker group
groups:
  - docker

# Install Docker, for production, consider pinning to stable versions
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - git clone https://github.com/infracost/cloud-pricing-api.git
  - echo "INFRACOST_API_KEY=${infracost_api_key}" > /cloud-pricing-api/.env
  - echo "SELF_HOSTED_INFRACOST_API_KEY=${self_hosted_api_key}" >> /cloud-pricing-api/.env
  - 0 4 * * SUN docker-compose -f /cloud-pricing-api/docker-compose.yml run --rm update_job npm run job:update >> /var/log/cron.log 2>&1
  - docker-compose -f /cloud-pricing-api/docker-compose.yml run init_job
  - docker-compose -f /cloud-pricing-api/docker-compose.yml up -d api

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]
